In [165]:
 import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [166]:
mv = ["na","-","n/a"]

In [167]:
list = ["10th score","12th score","JEE Mains","PI(Personal Interview)","Apptitude Score","Admitted or not?"]

In [168]:

dataset = pd.read_csv('datasetJobs.csv',na_values=mv)


In [169]:
#dataset[1:7].isnull().sum()
for i in list:
    dataset[i].isnull().sum()

In [170]:
for i in list:
    mean =dataset[i].mean()
    dataset[i].fillna(mean, inplace=True)

#mean =dataset[1:7].mean()
#dataset[1:7].fillna(mean, inplace=True)

In [171]:
X = dataset.iloc[:,1:6].values


In [172]:
y = dataset.iloc[:,6].values

In [173]:
X

array([[ 77.        ,  79.        , 105.        ,   3.        ,
          4.        ],
       [ 73.32323232,  74.        ,  95.        ,   2.        ,
          2.        ],
       [ 81.        ,  84.        , 110.        ,   4.        ,
          4.        ],
       [ 84.        ,  87.        , 110.52525253,   3.        ,
          4.        ],
       [ 60.        ,  71.        , 134.        ,   2.        ,
          3.        ],
       [ 61.        ,  64.        ,  89.        ,   1.        ,
          2.        ],
       [ 48.        ,  50.        ,  64.        ,   0.        ,
          2.38383838],
       [ 78.        ,  80.        , 107.        ,   2.        ,
          4.        ],
       [ 76.        ,  79.        , 110.        ,   3.        ,
          4.        ],
       [ 82.        ,  84.        ,  95.        ,   2.        ,
          2.        ],
       [ 88.        ,  90.        , 185.        ,   4.        ,
          4.        ],
       [ 89.        ,  91.        , 147.   

In [174]:
y

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [175]:


from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [176]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [177]:

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)



DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [178]:

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [179]:
y_test

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      dtype=int64)

In [180]:
y_pred

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      dtype=int64)